//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstructuraOrganizacional.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstructuraOrganizacional.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ana_Trujilo {
            get {
                object obj = ResourceManager.GetObject("Ana_Trujilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Andrew_Fuller {
            get {
                object obj = ResourceManager.GetObject("Andrew_Fuller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brenda_Smith {
            get {
                object obj = ResourceManager.GetObject("Brenda_Smith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Elizabeth_Lincoln {
            get {
                object obj = ResourceManager.GetObject("Elizabeth_Lincoln", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Georg_Pipps {
            get {
                object obj = ResourceManager.GetObject("Georg_Pipps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hanna_Moos {
            get {
                object obj = ResourceManager.GetObject("Hanna_Moos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janet_Levering {
            get {
                object obj = ResourceManager.GetObject("Janet_Levering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janine_Labrune {
            get {
                object obj = ResourceManager.GetObject("Janine_Labrune", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jason_Roland {
            get {
                object obj = ResourceManager.GetObject("Jason_Roland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jeremy_Boather {
            get {
                object obj = ResourceManager.GetObject("Jeremy_Boather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap John_Steel {
            get {
                object obj = ResourceManager.GetObject("John_Steel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karin_Josephs {
            get {
                object obj = ResourceManager.GetObject("Karin_Josephs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karl_Jablonski {
            get {
                object obj = ResourceManager.GetObject("Karl_Jablonski", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Laura_Callahan {
            get {
                object obj = ResourceManager.GetObject("Laura_Callahan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Margaret_Peacock {
            get {
                object obj = ResourceManager.GetObject("Margaret_Peacock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marie_Bertrand {
            get {
                object obj = ResourceManager.GetObject("Marie_Bertrand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Martin_Sommer {
            get {
                object obj = ResourceManager.GetObject("Martin_Sommer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mary_Saveley {
            get {
                object obj = ResourceManager.GetObject("Mary_Saveley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Moise_Gregoryy {
            get {
                object obj = ResourceManager.GetObject("Moise_Gregoryy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nancy_Davolio {
            get {
                object obj = ResourceManager.GetObject("Nancy_Davolio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;elements&gt;
        ///  &lt;element Id=&quot;7&quot; Name=&quot;DIRECCION &quot; Parent=&quot;DIRECCION&quot;&gt;
        ///    &lt;Child Id=&quot;6&quot; Name=&quot;Andrew Fuller&quot; Puesto=&quot;DIRECCION 1&quot; /&gt;
        ///    &lt;Child Id=&quot;5&quot; Name=&quot;Jason Roland&quot; Parent=&quot;DIRECCION 2&quot; /&gt;
        ///    &lt;Child Id=&quot;4&quot; Name=&quot;Martin Sommer&quot; Parent=&quot;DIRECCION 3&quot;&gt;
        ///    &lt;/Child&gt;
        ///       &lt;/element&gt;
        ///  &lt;element Id=&quot;7&quot; Name=&quot;VENTA &quot; Parent=&quot;VENTA&quot;&gt;
        ///    &lt;Child Id=&quot;3&quot; Name=&quot;Jeremy Boather&quot; Puesto=&quot;VENTA 1&quot;&gt; &lt;/Child&gt;
        ///      &lt;Child Id=&quot;2&quot; Name=&quot;John Steel &quot; Puesto=&quot;VENTA 2&quot;&gt;
        ///      &lt;/Child&gt;
        ///         &lt;/element&gt;
        ///  &lt;elemen [resto de la cadena truncado]&quot;;.
        /// </summary>
       
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Root&gt;
        ///	&lt;!--&lt;Node Name=&quot;ADMINISTRACION&quot; Area=&quot;DIRECCION&quot;&gt;
        ///    &lt;Child Name=&quot;Andrew Fuller&quot; Puesto=&quot;JEFE 1&quot; /&gt;
        ///    &lt;Child Name=&quot;Moise Gregoryy&quot; Puesto=&quot;BOSS&quot; /&gt;
        ///    &lt;Node Name=&quot;Direccion Hersan&quot; Area=&quot;Hersan&quot;&gt;
        ///      &lt;Child Name=&quot;Martin Sommer&quot; Puesto=&quot;Architect&quot; /&gt;
        ///      &lt;Child Name=&quot;Jeremy Boather&quot; Puesto=&quot;Senior Team Lead&quot; /&gt;
        ///      &lt;Child Name=&quot;John Steel&quot; Puesto=&quot;Development Manager&quot; /&gt;
        ///      &lt;Child Name=&quot;Karin Josephs&quot; Puesto=&quot;QA Architect&quot; /&gt;
        ///      &lt;Node  [resto de la cadena truncado]&quot;;.
        /// </summary>
      
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paula_Wilson {
            get {
                object obj = ResourceManager.GetObject("Paula_Wilson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pedro_Alfonso {
            get {
                object obj = ResourceManager.GetObject("Pedro_Alfonso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingsBlack {
            get {
                object obj = ResourceManager.GetObject("settingsBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steven_Buchanan {
            get {
                object obj = ResourceManager.GetObject("Steven_Buchanan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Viktoria_Ashworth {
            get {
                object obj = ResourceManager.GetObject("Viktoria_Ashworth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
