//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hersan.UI.Ventas.WCF_Ventas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Ventas.IHersan_Ventas")]
    public interface IHersan_Ventas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_Clientes_Guardar", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_Clientes_GuardarResponse")]
        int ABC_Clientes_Guardar(System.Data.DataSet Tablas, string Entidades, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_Clientes_Buscar", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_Clientes_BuscarResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Ventas.ClientesBE> ABC_Clientes_Buscar(Hersan.Entidades.Ventas.ClientesBE Lista, string Entidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_Clientes_Obtener", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_Clientes_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Ventas.ClientesBE> ABC_Clientes_Obtener(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_FormaPago_Combo", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_FormaPago_ComboResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Catalogos.FormasPagoBE> ABC_FormaPago_Combo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_MetodoPago_Combo", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_MetodoPago_ComboResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Catalogos.MetodosPagoBE> ABC_MetodoPago_Combo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Ventas/ABC_UsoCFDI_Combo", ReplyAction="http://tempuri.org/IHersan_Ventas/ABC_UsoCFDI_ComboResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Catalogos.UsoCFDIBE> ABC_UsoCFDI_Combo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHersan_VentasChannel : Hersan.UI.Ventas.WCF_Ventas.IHersan_Ventas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Hersan_VentasClient : System.ServiceModel.ClientBase<Hersan.UI.Ventas.WCF_Ventas.IHersan_Ventas>, Hersan.UI.Ventas.WCF_Ventas.IHersan_Ventas {
        
        public Hersan_VentasClient() {
        }
        
        public Hersan_VentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Hersan_VentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_VentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_VentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ABC_Clientes_Guardar(System.Data.DataSet Tablas, string Entidades, int IdUsuario) {
            return base.Channel.ABC_Clientes_Guardar(Tablas, Entidades, IdUsuario);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Ventas.ClientesBE> ABC_Clientes_Buscar(Hersan.Entidades.Ventas.ClientesBE Lista, string Entidades) {
            return base.Channel.ABC_Clientes_Buscar(Lista, Entidades);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Ventas.ClientesBE> ABC_Clientes_Obtener(int IdCliente) {
            return base.Channel.ABC_Clientes_Obtener(IdCliente);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Catalogos.FormasPagoBE> ABC_FormaPago_Combo() {
            return base.Channel.ABC_FormaPago_Combo();
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Catalogos.MetodosPagoBE> ABC_MetodoPago_Combo() {
            return base.Channel.ABC_MetodoPago_Combo();
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Catalogos.UsoCFDIBE> ABC_UsoCFDI_Combo() {
            return base.Channel.ABC_UsoCFDI_Combo();
        }
    }
}
