//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hersan.UI.Nomina.WCF_Nomina {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Nomina.IHersan_Nomina")]
    public interface IHersan_Nomina {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/Nom_Factores_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/Nom_Factores_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.FactoresBE> Nom_Factores_Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Subsidios_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Subsidios_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.SubsidiosBE> NOM_Subsidios_Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_ISR_Semanal_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_ISR_Semanal_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.ISRBE> NOM_ISR_Semanal_Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Semanas_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Semanas_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.SemanasBE> NOM_Semanas_Obtener(int Anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Semanas_generar", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Semanas_generarResponse")]
        int NOM_Semanas_generar(int Anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Cuotas_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Cuotas_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.CuotasBE> NOM_Cuotas_Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/Nom_Parametros_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/Nom_Parametros_ObtenerResponse")]
        Hersan.Entidades.Nomina.ParametrosBE Nom_Parametros_Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/Nom_Parametros_Guardar", ReplyAction="http://tempuri.org/IHersan_Nomina/Nom_Parametros_GuardarResponse")]
        int Nom_Parametros_Guardar(Hersan.Entidades.Nomina.ParametrosBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_CalculoNomina", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_CalculoNominaResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.NominaBE> NOM_CalculoNomina(int Semana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Prestamos_Guardar", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Prestamos_GuardarResponse")]
        int NOM_Prestamos_Guardar(Hersan.Entidades.Nomina.PrestamosBE Obj, System.Data.DataTable Detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Incidencias_Guardar", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Incidencias_GuardarResponse")]
        int NOM_Incidencias_Guardar(System.Collections.Generic.List<Hersan.Entidades.Nomina.IncidenciasBE> Lista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Nomina/NOM_Incidencias_Obtener", ReplyAction="http://tempuri.org/IHersan_Nomina/NOM_Incidencias_ObtenerResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Nomina.IncidenciasBE> NOM_Incidencias_Obtener(int Semana);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHersan_NominaChannel : Hersan.UI.Nomina.WCF_Nomina.IHersan_Nomina, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Hersan_NominaClient : System.ServiceModel.ClientBase<Hersan.UI.Nomina.WCF_Nomina.IHersan_Nomina>, Hersan.UI.Nomina.WCF_Nomina.IHersan_Nomina {
        
        public Hersan_NominaClient() {
        }
        
        public Hersan_NominaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Hersan_NominaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_NominaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_NominaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.FactoresBE> Nom_Factores_Obtener() {
            return base.Channel.Nom_Factores_Obtener();
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.SubsidiosBE> NOM_Subsidios_Obtener() {
            return base.Channel.NOM_Subsidios_Obtener();
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.ISRBE> NOM_ISR_Semanal_Obtener() {
            return base.Channel.NOM_ISR_Semanal_Obtener();
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.SemanasBE> NOM_Semanas_Obtener(int Anio) {
            return base.Channel.NOM_Semanas_Obtener(Anio);
        }
        
        public int NOM_Semanas_generar(int Anio) {
            return base.Channel.NOM_Semanas_generar(Anio);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.CuotasBE> NOM_Cuotas_Obtener() {
            return base.Channel.NOM_Cuotas_Obtener();
        }
        
        public Hersan.Entidades.Nomina.ParametrosBE Nom_Parametros_Obtener() {
            return base.Channel.Nom_Parametros_Obtener();
        }
        
        public int Nom_Parametros_Guardar(Hersan.Entidades.Nomina.ParametrosBE item) {
            return base.Channel.Nom_Parametros_Guardar(item);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.NominaBE> NOM_CalculoNomina(int Semana) {
            return base.Channel.NOM_CalculoNomina(Semana);
        }
        
        public int NOM_Prestamos_Guardar(Hersan.Entidades.Nomina.PrestamosBE Obj, System.Data.DataTable Detalle) {
            return base.Channel.NOM_Prestamos_Guardar(Obj, Detalle);
        }
        
        public int NOM_Incidencias_Guardar(System.Collections.Generic.List<Hersan.Entidades.Nomina.IncidenciasBE> Lista) {
            return base.Channel.NOM_Incidencias_Guardar(Lista);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Nomina.IncidenciasBE> NOM_Incidencias_Obtener(int Semana) {
            return base.Channel.NOM_Incidencias_Obtener(Semana);
        }
    }
}
