//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hersan.UI.Seguridad.WCF_Seguridad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Seguridad.IHersan_Seguridad")]
    public interface IHersan_Seguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtenerMenuUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtenerMenuUsuarioResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> ObtenerMenuUsuario(string Usuario, int Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtenerMenuUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtenerMenuUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE>> ObtenerMenuUsuarioAsync(string Usuario, int Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtenerMenuRol", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtenerMenuRolResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> ObtenerMenuRol(int Rol, int Padre, int Menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtenerMenuRol", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtenerMenuRolResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE>> ObtenerMenuRolAsync(int Rol, int Padre, int Menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaMenuRol", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaMenuRolResponse")]
        void GuardaMenuRol(System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> lstMnu, int Rol, int Menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaMenuRol", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaMenuRolResponse")]
        System.Threading.Tasks.Task GuardaMenuRolAsync(System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> lstMnu, int Rol, int Menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ValidaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ValidaUsuarioResponse")]
        Hersan.Entidades.Seguridad.ValidaIngresoBE ValidaUsuario(string nomUsr, string Pswd, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ValidaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ValidaUsuarioResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.ValidaIngresoBE> ValidaUsuarioAsync(string nomUsr, string Pswd, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtienBloqueoUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtienBloqueoUsuarioResponse")]
        Hersan.Entidades.Seguridad.ValidaIngresoBE ObtienBloqueoUsuario(string nomUsr, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtienBloqueoUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtienBloqueoUsuarioResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.ValidaIngresoBE> ObtienBloqueoUsuarioAsync(string nomUsr, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/DesbloqueaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/DesbloqueaUsuarioResponse")]
        void DesbloqueaUsuario(string nomUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/DesbloqueaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/DesbloqueaUsuarioResponse")]
        System.Threading.Tasks.Task DesbloqueaUsuarioAsync(string nomUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneUsuarios", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneUsuariosResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Seguridad.UsuariosBE> ObtieneUsuarios(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneUsuarios", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.UsuariosBE>> ObtieneUsuariosAsync(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaUsuarioResponse")]
        Hersan.Entidades.Comun.ResultadoBE GuardaUsuario(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioCrea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaUsuarioResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> GuardaUsuarioAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioCrea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ActualizaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ActualizaUsuarioResponse")]
        Hersan.Entidades.Comun.ResultadoBE ActualizaUsuario(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioMod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ActualizaUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ActualizaUsuarioResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> ActualizaUsuarioAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioMod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneDatosUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneDatosUsuarioResponse")]
        Hersan.Entidades.Seguridad.UsuariosBE ObtieneDatosUsuario(string Usuario, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneDatosUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneDatosUsuarioResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.UsuariosBE> ObtieneDatosUsuarioAsync(string Usuario, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/CambiaContrasenia", ReplyAction="http://tempuri.org/IHersan_Seguridad/CambiaContraseniaResponse")]
        int CambiaContrasenia(Hersan.Entidades.Seguridad.UsuariosBE Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/CambiaContrasenia", ReplyAction="http://tempuri.org/IHersan_Seguridad/CambiaContraseniaResponse")]
        System.Threading.Tasks.Task<int> CambiaContraseniaAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneRolesResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE> ObtieneRoles(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneRolesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE>> ObtieneRolesAsync(int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaRolesResponse")]
        Hersan.Entidades.Comun.ResultadoBE GuardaRoles(string Rol, int IdEmpresa, int IdUsuario, bool Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaRolesResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> GuardaRolesAsync(string Rol, int IdEmpresa, int IdUsuario, bool Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ActualizaRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/ActualizaRolesResponse")]
        Hersan.Entidades.Comun.ResultadoBE ActualizaRoles(int IdRol, string Rol, int IdEmpresa, int IdUsuario, bool Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ActualizaRoles", ReplyAction="http://tempuri.org/IHersan_Seguridad/ActualizaRolesResponse")]
        System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> ActualizaRolesAsync(int IdRol, string Rol, int IdEmpresa, int IdUsuario, bool Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneRolesUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneRolesUsuarioResponse")]
        System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE> ObtieneRolesUsuario(int IdUsuario, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/ObtieneRolesUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/ObtieneRolesUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE>> ObtieneRolesUsuarioAsync(int IdUsuario, int IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaRolesUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaRolesUsuarioResponse")]
        void GuardaRolesUsuario(int IdRol, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHersan_Seguridad/GuardaRolesUsuario", ReplyAction="http://tempuri.org/IHersan_Seguridad/GuardaRolesUsuarioResponse")]
        System.Threading.Tasks.Task GuardaRolesUsuarioAsync(int IdRol, int IdUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHersan_SeguridadChannel : Hersan.UI.Seguridad.WCF_Seguridad.IHersan_Seguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Hersan_SeguridadClient : System.ServiceModel.ClientBase<Hersan.UI.Seguridad.WCF_Seguridad.IHersan_Seguridad>, Hersan.UI.Seguridad.WCF_Seguridad.IHersan_Seguridad {
        
        public Hersan_SeguridadClient() {
        }
        
        public Hersan_SeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Hersan_SeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_SeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hersan_SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> ObtenerMenuUsuario(string Usuario, int Empresa) {
            return base.Channel.ObtenerMenuUsuario(Usuario, Empresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE>> ObtenerMenuUsuarioAsync(string Usuario, int Empresa) {
            return base.Channel.ObtenerMenuUsuarioAsync(Usuario, Empresa);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> ObtenerMenuRol(int Rol, int Padre, int Menu) {
            return base.Channel.ObtenerMenuRol(Rol, Padre, Menu);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE>> ObtenerMenuRolAsync(int Rol, int Padre, int Menu) {
            return base.Channel.ObtenerMenuRolAsync(Rol, Padre, Menu);
        }
        
        public void GuardaMenuRol(System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> lstMnu, int Rol, int Menu) {
            base.Channel.GuardaMenuRol(lstMnu, Rol, Menu);
        }
        
        public System.Threading.Tasks.Task GuardaMenuRolAsync(System.Collections.Generic.List<Hersan.Entidades.Seguridad.MenusBE> lstMnu, int Rol, int Menu) {
            return base.Channel.GuardaMenuRolAsync(lstMnu, Rol, Menu);
        }
        
        public Hersan.Entidades.Seguridad.ValidaIngresoBE ValidaUsuario(string nomUsr, string Pswd, int IdEmpresa) {
            return base.Channel.ValidaUsuario(nomUsr, Pswd, IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.ValidaIngresoBE> ValidaUsuarioAsync(string nomUsr, string Pswd, int IdEmpresa) {
            return base.Channel.ValidaUsuarioAsync(nomUsr, Pswd, IdEmpresa);
        }
        
        public Hersan.Entidades.Seguridad.ValidaIngresoBE ObtienBloqueoUsuario(string nomUsr, int IdEmpresa) {
            return base.Channel.ObtienBloqueoUsuario(nomUsr, IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.ValidaIngresoBE> ObtienBloqueoUsuarioAsync(string nomUsr, int IdEmpresa) {
            return base.Channel.ObtienBloqueoUsuarioAsync(nomUsr, IdEmpresa);
        }
        
        public void DesbloqueaUsuario(string nomUsr) {
            base.Channel.DesbloqueaUsuario(nomUsr);
        }
        
        public System.Threading.Tasks.Task DesbloqueaUsuarioAsync(string nomUsr) {
            return base.Channel.DesbloqueaUsuarioAsync(nomUsr);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Seguridad.UsuariosBE> ObtieneUsuarios(int IdEmpresa) {
            return base.Channel.ObtieneUsuarios(IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.UsuariosBE>> ObtieneUsuariosAsync(int IdEmpresa) {
            return base.Channel.ObtieneUsuariosAsync(IdEmpresa);
        }
        
        public Hersan.Entidades.Comun.ResultadoBE GuardaUsuario(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioCrea) {
            return base.Channel.GuardaUsuario(Usuario, IdUsuarioCrea);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> GuardaUsuarioAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioCrea) {
            return base.Channel.GuardaUsuarioAsync(Usuario, IdUsuarioCrea);
        }
        
        public Hersan.Entidades.Comun.ResultadoBE ActualizaUsuario(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioMod) {
            return base.Channel.ActualizaUsuario(Usuario, IdUsuarioMod);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> ActualizaUsuarioAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario, int IdUsuarioMod) {
            return base.Channel.ActualizaUsuarioAsync(Usuario, IdUsuarioMod);
        }
        
        public Hersan.Entidades.Seguridad.UsuariosBE ObtieneDatosUsuario(string Usuario, int IdEmpresa) {
            return base.Channel.ObtieneDatosUsuario(Usuario, IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Seguridad.UsuariosBE> ObtieneDatosUsuarioAsync(string Usuario, int IdEmpresa) {
            return base.Channel.ObtieneDatosUsuarioAsync(Usuario, IdEmpresa);
        }
        
        public int CambiaContrasenia(Hersan.Entidades.Seguridad.UsuariosBE Usuario) {
            return base.Channel.CambiaContrasenia(Usuario);
        }
        
        public System.Threading.Tasks.Task<int> CambiaContraseniaAsync(Hersan.Entidades.Seguridad.UsuariosBE Usuario) {
            return base.Channel.CambiaContraseniaAsync(Usuario);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE> ObtieneRoles(int IdEmpresa) {
            return base.Channel.ObtieneRoles(IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE>> ObtieneRolesAsync(int IdEmpresa) {
            return base.Channel.ObtieneRolesAsync(IdEmpresa);
        }
        
        public Hersan.Entidades.Comun.ResultadoBE GuardaRoles(string Rol, int IdEmpresa, int IdUsuario, bool Estatus) {
            return base.Channel.GuardaRoles(Rol, IdEmpresa, IdUsuario, Estatus);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> GuardaRolesAsync(string Rol, int IdEmpresa, int IdUsuario, bool Estatus) {
            return base.Channel.GuardaRolesAsync(Rol, IdEmpresa, IdUsuario, Estatus);
        }
        
        public Hersan.Entidades.Comun.ResultadoBE ActualizaRoles(int IdRol, string Rol, int IdEmpresa, int IdUsuario, bool Estatus) {
            return base.Channel.ActualizaRoles(IdRol, Rol, IdEmpresa, IdUsuario, Estatus);
        }
        
        public System.Threading.Tasks.Task<Hersan.Entidades.Comun.ResultadoBE> ActualizaRolesAsync(int IdRol, string Rol, int IdEmpresa, int IdUsuario, bool Estatus) {
            return base.Channel.ActualizaRolesAsync(IdRol, Rol, IdEmpresa, IdUsuario, Estatus);
        }
        
        public System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE> ObtieneRolesUsuario(int IdUsuario, int IdEmpresa) {
            return base.Channel.ObtieneRolesUsuario(IdUsuario, IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hersan.Entidades.Seguridad.RolesBE>> ObtieneRolesUsuarioAsync(int IdUsuario, int IdEmpresa) {
            return base.Channel.ObtieneRolesUsuarioAsync(IdUsuario, IdEmpresa);
        }
        
        public void GuardaRolesUsuario(int IdRol, int IdUsuario) {
            base.Channel.GuardaRolesUsuario(IdRol, IdUsuario);
        }
        
        public System.Threading.Tasks.Task GuardaRolesUsuarioAsync(int IdRol, int IdUsuario) {
            return base.Channel.GuardaRolesUsuarioAsync(IdRol, IdUsuario);
        }
    }
}
